// Generated by gencpp from file retina_view/Point.msg
// DO NOT EDIT!


#ifndef RETINA_VIEW_MESSAGE_POINT_H
#define RETINA_VIEW_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace retina_view
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , doppler(0.0)
    , cluster(0)
    , power(0)
    , track(0)  {
    }
  Point_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , doppler(0.0)
    , cluster(0)
    , power(0)
    , track(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _doppler_type;
  _doppler_type doppler;

   typedef uint32_t _cluster_type;
  _cluster_type cluster;

   typedef uint32_t _power_type;
  _power_type power;

   typedef uint8_t _track_type;
  _track_type track;





  typedef boost::shared_ptr< ::retina_view::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::retina_view::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::retina_view::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::retina_view::Point > PointPtr;
typedef boost::shared_ptr< ::retina_view::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::retina_view::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::retina_view::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::retina_view::Point_<ContainerAllocator1> & lhs, const ::retina_view::Point_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.doppler == rhs.doppler &&
    lhs.cluster == rhs.cluster &&
    lhs.power == rhs.power &&
    lhs.track == rhs.track;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::retina_view::Point_<ContainerAllocator1> & lhs, const ::retina_view::Point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace retina_view

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::retina_view::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::retina_view::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::retina_view::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::retina_view::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::retina_view::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::retina_view::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::retina_view::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e40ec70d104bb5b08bfb46fbc12725d";
  }

  static const char* value(const ::retina_view::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e40ec70d104bb5bULL;
  static const uint64_t static_value2 = 0x08bfb46fbc12725dULL;
};

template<class ContainerAllocator>
struct DataType< ::retina_view::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "retina_view/Point";
  }

  static const char* value(const ::retina_view::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::retina_view::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 doppler\n"
"uint32 cluster\n"
"uint32 power\n"
"uint8 track\n"
;
  }

  static const char* value(const ::retina_view::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::retina_view::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.doppler);
      stream.next(m.cluster);
      stream.next(m.power);
      stream.next(m.track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::retina_view::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::retina_view::Point_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "doppler: ";
    Printer<float>::stream(s, indent + "  ", v.doppler);
    s << indent << "cluster: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cluster);
    s << indent << "power: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.power);
    s << indent << "track: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.track);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RETINA_VIEW_MESSAGE_POINT_H
